# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main  # Trigger this pipeline when changes are pushed to the 'main' branch

pool:
  name: 'COMP367-Pstellak'  # Use your self-hosted agent pool for this pipeline

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Use .NET 6 SDK
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Build the project(s)
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'  # Build all .csproj files in the repository

# Publish the project(s)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'  # Publish with Release configuration

# Publish the build artifact so it can be consumed by the release pipeline
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'  # Name the artifact as 'drop'
    publishLocation: 'Container'  # Publish the artifact to the build container
