trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline  # Alias for the referenced pipeline
      source: Stella_Question2  # Ensure this matches the name of the pipeline you're referencing
      trigger: none

stages:
- stage: DeployWebApp
  displayName: "Deploy to Environment (Virtual Machine)"
  jobs:
  - deployment: DeployASPNetApp
    displayName: "Deploy to Lab4Environment VM"
    environment:
      name: Lab4Environment
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - download: buildPipeline  # Download the artifact from the referenced pipeline
            artifact: drop  # Ensure this matches the artifact name from the build pipeline

          # Create the folder before copying
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                New-Item -ItemType Directory -Force -Path "C:\Deployments\MyWebApp"

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/drop'
              Contents: '**'
              TargetFolder: 'C:\\Deployments\\MyWebApp'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "✅ Deployment complete to C:\\Deployments\\MyWebApp"
