# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name:  COMP367-Pstellak  # your self-hosted agent pool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0'

- script: dotnet build
  displayName: 'Build app'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

