trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    exclude:
      - '*'

stages:
- stage: Deploy
  jobs:
    - job: DeployToSelfHostedAgent
      displayName: 'Deploy Web App to Self-hosted Agent'
      pool:
        name: ' COMP367-Pstellak'
      steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'specific'
            project: '$(System.TeamProject)'
            definition: 'Your-Build-Pipeline-Name'  # Replace with your actual CI pipeline name
            buildVersionToDownload: 'latest'
            downloadType: 'single'
            artifactName: 'drop'  # Name of the artifact in your CI pipeline
            targetPath: '$(Build.ArtifactStagingDirectory)'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.ArtifactStagingDirectory)/drop'
            Contents: '**'
            TargetFolder: '$(Agent.TempDirectory)/drop'

        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'Your Azure Subscription'  # Replace with your Azure subscription
            appName: 'Your-Web-App-Name'  # Replace with your Azure Web App name
            package: '$(Agent.TempDirectory)/drop/**/*.zip'  # Path to your package/artifact
